In [1]:
#import the libiraries
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import LabelEncoder

In [3]:
#Load the dataset
df = pd.read_csv('../data/car data.csv')

In [4]:
#Show the original shape of the dataset
df.shape

(301, 9)

In [5]:
df.head()

  Car_Name  Year  Selling_Price  ...  Selling_type  Transmission Owner
0     ritz  2014           3.35  ...        Dealer        Manual     0
1      sx4  2013           4.75  ...        Dealer        Manual     0
2     ciaz  2017           7.25  ...        Dealer        Manual     0
3  wagon r  2011           2.85  ...        Dealer        Manual     0
4    swift  2014           4.60  ...        Dealer        Manual     0

[5 rows x 9 columns]

In [6]:
#check the catogorical columns
print("Categorical columns: ")
print(df.select_dtypes(include='object').columns.tolist())

Categorical columns:
['Car_Name', 'Fuel_Type', 'Selling_type', 'Transmission']

C:\Users\user\AppData\Local\Temp\ipykernel_21164\3665204349.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include='object').columns.tolist())

In [8]:
# Encode categorical columns
le=LabelEncoder()
df['Fuel_Type']=le.fit_transform(df['Fuel_Type'])
df['Selling_type']=le.fit_transform(df['Selling_type'])
df['Transmission']=le.fit_transform(df['Transmission'])

print("After encoding the categorical columns: ")
df.head()

After encoding the categorical columns:

  Car_Name  Year  Selling_Price  ...  Selling_type  Transmission  Owner
0     ritz  2014           3.35  ...             0             1      0
1      sx4  2013           4.75  ...             0             1      0
2     ciaz  2017           7.25  ...             0             1      0
3  wagon r  2011           2.85  ...             0             1      0
4    swift  2014           4.60  ...             0             1      0

[5 rows x 9 columns]

In [10]:
# Droping the car name is not useful for the model training
df.drop(['Car_Name'], axis=1, inplace=True)
print("Shape after dropping the car name column: ", df.shape)

Shape after dropping the car name column:  (301, 8)

In [12]:
#sparate features and target 
X=df.drop('Selling_Price',axis=1)
y=df['Selling_Price']

print("Features shape:", X.shape)
print("Target shape:", y.shape)
print("\nFeatures:")
print(X.columns.tolist())

Features shape: (301, 7)
Target shape: (301,)

Features:
['Year', 'Present_Price', 'Driven_kms', 'Fuel_Type', 'Selling_type', 'Transmission', 'Owner']

In [13]:
#Split data
from sklearn.model_selection import train_test_split
X_train, X_test ,y_train , y_test=train_test_split(
    X ,y ,test_size=0.2 ,random_state=42
)
print("Train size: ",X_train.shape)
print("test size: ",X_test.shape)

Train size:  (240, 7)
test size:  (61, 7)

In [14]:
#Save processed data 
X_train.to_csv('../data/X_train.csv', index=False)
X_test.to_csv('../data/X_test.csv', index=False)
y_train.to_csv('../data/y_train.csv', index=False)
y_test.to_csv('../data/y_test.csv', index=False)

print("Data saved successfully!")

Data saved successfully!